version: '3'

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        user: root
        volumes:
            - ./monitor/prometheus/config:/etc/prometheus
            - ./monitor/prometheus/data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention=15d'
            - '--web.enable-lifecycle'
        ports:
            - "9090:9090"
        networks:
            - monitor

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        user: root
        volumes:
            - ./monitor/alertmanager/config:/etc/alertmanager
        ports:
            - "9093:9093"
        networks:
            - monitor

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        user: root
        volumes:
            - ./monitor/grafana/data:/var/lib/grafana
        ports:
            - "3000:3000"
        networks:
            - monitor
            
    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        user: root
        ports:
            - "9100:9100"
        networks:
            - monitor

    consul:
        image: consul
        container_name: "consul"
        restart: always
        user: root
        ports:
          - "8500:8500"
        volumes:
          - ./monitor/consul/data:/consul/data
        command: [agent,-server,-ui,-client=0.0.0.0,-bootstrap-expect=1]



