version: '2'
services:
  redis:
    restart: always
    image: redis/redis-stack:latest
    container_name: redis
    volumes:
      - ${REDIS_DIR}/data:/data
      - ${REDIS_DIR}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_DIR}/logs:/logs
      - ${REDIS_DIR}/module/rejson.so:/opt/redis/module/rejson.so
    command: 
      - /bin/bash
      - -c
      - |
         redis-server /usr/local/etc/redis/redis.conf
         redis-server --requirepass redis
    ports:
      # 使用宿主机的端口映射到容器的端口
      # 宿主机：容器
      - 6379:6379